pipeline:
  build:
    image: node
    pull: true
    commands:
      - yarn install
      - yarn build
      - yarn benchmark
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  github_release:
    image: plugins/github-release
    files: dist/*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event: tag
  
  npm:
    image: plugins/npm
    username: prefixaut
    email: mail@prefix.moe
    password: <todo>
    folder: dist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event: tag
