language: node_js
node_js:
  - "node"
  - "iojs"
  - "lts/*"
  - "8"
  - "7"

matrix:
  allow_failures:
    - node_js: "node"
    - node_js: "iojs"

cache:
  directories:
    - "node_modules"

notifications:
  email: false

install: npm install

# Setting up Code-Climate
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Build the project and run coverage tests
script:
  - npm run build
  - npm run coverage

# Sending results to Code-Climate
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  - provider: npm
    email: me@prefixaut.net
    api_key:
      secure: TODO
    on:
      tags: true
      repo: prefixaut/aevum
      branch: master
  - provider: releases
    api_key:
      secure: TODO
    file:
      - dist/aevum.d.ts
      - dist/aevum.js
      - dist/aevum.js.map
      - dist/compiler.d.ts
      - dist/compiler.js
      - dist/compiler.js.map
      - dist/tokenizer.d.ts
      - dist/tokenizer.js
      - dist/tokenizer.js.map
      - src/aevum.ts
      - src/compiler.ts
      - src/tokenizer.ts
    skip_cleanup: true
    on:
      tags: true
      repo: prefixaut/aevum
      branch: master