language: node_js

node_js:
- node
- lts/*

cache:
  directories:
  - node_modules

notifications:
  email: false

install: yarn

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"

script:
- yarn run build
- yarn run benchmark
- yarn run coverage

after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

deploy:
- provider: npm
  email: mail@prefix.moe
  api_key:
    secure: qHVgRVMYuCdhTR9kbze0Rch2LCrTy12mS83mHvA6Fbfl32zqwU3DHepHC0ag6020DeWDb7mssjqC2QIYVvjHdvCgc7FVk9vq90T5yQXOfXqKlpo+ff2OJBgx2Ep1j/x3BqwK6UnCcwf3JOHXL3EmDGAGP3ea0bVqLy4uB9gzNKKussPyvsAfdJQnY0DeiHr/fkDGwThg0jBBUnNhYTZTFIrdCnHPxu4k91eMy8mquf0qbEqQ2Tdso1Xmpf8nRVGHPZLHOmnPBJz6/KFJEGmHLyTs8MQIdVtRZkmrl/tQqlJSv0KUtdaOqyTjUkjm4nmMj8GFRsz4LxsIOAOIndiE06HpdjKKYkzpxfgQcP1EH+TpdmsBtueP6e+jhEwJOjyR3HbXZLIYyjdwdznzEqucmfaMIR07dRZhtEEaU6G5/PxNiKzud3eQSeXqZK1LLGRMsqVxD2AwoOvjKZ7yLvhSegyz9sWSvY89fuhelXnxkoRH4gurL6aTcv2Dcz/Xb/kXeGFheaAsvsujJl3DPh7rW3fLNVAZ7N+LHEFLTMbSF2fuMTV8QSXAzGuC+5n5mIWQdTfsb8+w7q65nIaCk9a1h8FELJI0FWeN7VG49oEyFvca/jbRE6Pvea2IvAcqGlqThfsmsLE4av7Zvpfn/TC1C72DqGMC1CHEEWKqHh2lSsg=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG == release-*"
- provider: releases
  api_key:
    secure: eklcITtVdzS6UMVz4ejF8f+lUJcS/wmco/D+hECGFLHO7x/HQJlDd+LDIuqc5pXufMyNf9JvuJJ4SZyWZQBgu1ZfxJVgC9zDsesP1PINJ2pHEmrUBe9Lr3MM+d1gH+Ljzz/d0ACnr7th6xcWgAXneh9pufrvGSvoqGc7VEZFKZ4NiXINTp+WufXKLPn3pHsTl2WEFOstG5WHFiOSYGLFAoLrLVa4Db8jghDDQicsOxRnKlnNk2grkfelFweCuDnAP4XdbmTtwCxmqvXM2bw5hglZ7Oe2YxI36HAZsPEc8qVH4jt9lZ/7Gx1SQmNrtTGLIoIvPoUG9domOh9Y7eCj0+ehws1g/IyKl5O8YgJlbgcy3aKyn1F8Y3eesbUuRWAXlAV7/RUNHU7NAwEuQXhya8KJxEBd2j8/hT2fz99pTM3OquxjOhIpLRYtsQ5sknjLQJx5DPbuqrjK8QHYNNFmOyrYXdNMC7YNRXmwUPZySLEkEgkGKJNzbdA0Fxubd1vbQsi0P8Bs90Jybp4maHeDwid/kY4Wprta4o1qxEfRn2+ykI1NwwZyKhgpWvwPHvSqaMtx+wMy6enrtH+YR/awqnxYlrKQ+GvXKox5DgCPa98HLkBPSHc81Dn/0GnGTSJC+YLVhJT2NbnJcqZuwthPgt3Z3Zb+E5tK0gZZXhglze8=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG == release-*"
